### DISCUSSION TITLE
Add support of package `fontconfig` on java buildpack

### DISCUSSION THREAD

**Discussion by ldominguezBold** [paketo-buildpacks/feedback#203] [Java Team]
Hi, I have jhipster (spring boot) java project that use the Graphics2D stack of java to build a png image rendering a text inside it. I'm using the full stack `paketobuildpacks/builder-jammy-base`, i was searching a method to install into the final image this apt package but the only thing that i found is to create a custom stack with this. There is no way to add an additional build like the apt-buildpackage or some environment that add this specific package to the ubuntu run image?

**Comment by dmikusa** [comment]
For now, option 4.) here is the best choice.

https://stackoverflow.com/questions/69447497/is-it-possible-to-customize-docker-image-generated-with-spring-native-with-buil/69466535#69466535

It can be used to install additional packages. I haven't done this in a while, but you may need to point the JVM to the location into which the packages are installed. The apt-buildpack tries to set up env variables to make things discoverable, but it doesn't always work.

In the future, we'll be able to support this better through buildpack extensions. Those are not quite ready yet though.

**Reply by ldominguezBold** [reply]
thanks

**Reply by ldominguezBold** [reply]
But the thing with 4) is the add of this build-pack... I'm using this script to avoid to use docker on build (I'm on Gitlab CI with a runner inside kubernetes that dont use docker):
```yaml
make_image:
  image: paketobuildpacks/builder-jammy-base
  stage: package 
  script:
    - mkdir ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" >> ~/.docker/config.json
    - /cnb/lifecycle/creator -app=. $CI_REGISTRY_IMAGE:latest
```
how add this apt build-pack there?
