### DISCUSSION TITLE
Alternate JVM / ca-certificates

### DISCUSSION THREAD

**Discussion by alexist** [paketo-buildpacks/feedback#310] [Java Team]
Hi,

I'm using buildpack paketo-buildpacks/amazon-corretto as alternate JVM. To provide a custom CA in the JVM truststore, i'have followed the advice found here :  https://paketo.io/docs/howto/java/#use-an-alternative-jvm

I put in my project.toml the buildpacks : 

```toml
[[build.buildpacks]]
uri = "paketo-buildpacks/ca-certificates:3"

[[build.buildpacks]]
uri = "paketo-buildpacks/amazon-corretto"

[[build.buildpacks]]
uri = "paketo-buildpacks/java"
```

As you can see, i had to put a version in "ca-certificates", otherwise this error was thrown : `processing buildpacks order: unable to resolve version: multiple version` :

```console
Status: Image is up to date for paketobuildpacks/run-jammy-base:latest
docker.io/paketobuildpacks/amazon-corretto@sha256:273cf375d077c9e58ca909fe8eee2e357a97e237dcca88158f142eb65a72fb04: Pulling from paketobuildpacks/amazon-corretto
Digest: sha256:273cf375d077c9e58ca909fe8eee2e357a97e237dcca88158f142eb65a72fb04
Status: Image is up to date for paketobuildpacks/amazon-corretto@sha256:273cf375d077c9e58ca909fe8eee2e357a97e237dcca88158f142eb65a72fb04
Warning: Builder is trusted but additional modules were added; using the untrusted (5 phases) build flow
0.20.1: Pulling from buildpacksio/lifecycle
Digest: sha256:79de471d31b30de35c923cbad9706ebdd6bd12f268e7efeb42[52](https://git.orion.s2e-net.com/api-gateway/oauth2-bff/-/jobs/1425220#L52)01e7cd5a87b7
Status: Image is up to date for buildpacksio/lifecycle:0.20.1
ERROR: failed to build: processing buildpacks order: unable to resolve version: multiple versions of 'paketo-buildpacks/ca-certificates' - must specify an explicit version
```

I would prefer not to fix a version in ca-certificates, I just want to order the buildpacks.

Is there a way to do this ?
