### DISCUSSION TITLE
paketo buildpacks bellsoft-liberica: wrong path during memory-calculator execution

### DISCUSSION THREAD

**Discussion by NValanos** [paketo-buildpacks/feedback#328] [Dependencies Team]
Hi all,

I have a spring-boot maven project that consists of multiple inner projects and I need to create docker images for the 2 inner projects. An example of the structure would be the following:

 - service-api-parent
   - | pom.xml  
   - | service-api
       - | pom.xml
   - | service-simulator
       - | pom.xml

Due to the fact that the building process needs to run on a non-docker gitlab runner, I'm using the 'creator' command immediately from the pre-loaded 'paketobuildpacks/builder-jammy-base' image. The .gitlab.ci job looks like this:

```
deploy-images:
  stage: deploy-images
  image:
    name: paketobuildpacks/builder-jammy-base
    docker:
      user: root
  script:
    - echo "target/*-exec.[ejw]ar" > /platform/env/BP_MAVEN_BUILT_ARTIFACT
    - export CNB_PLATFORM_API=0.14
    - echo "8" > /platform/env/BP_JVM_VERSION 
    - cd service-api
    - /cnb/lifecycle/creator -app=. $CI_REGISTRY/service-api:1.0.0
    - cd ../service-simulator
    - /cnb/lifecycle/creator -app=. $CI_REGISTRY/service-simulator:1.0.0
```

As you can see, I need to build 2 images, one for the service-api and one for the service-simulator.
The build succeeds and the images are uploaded in the gitlab's container-registry. Also, when I try to create containers based on these images, everything works fine.

The problem occurs when I need to re-build the images based on a new version, for example:

```
   ...
    - cd service-api
    - /cnb/lifecycle/creator -app=. $CI_REGISTRY/service-api:1.1.0
    - cd ../service-simulator
    - /cnb/lifecycle/creator -app=. $CI_REGISTRY/service-simulator:1.1.0
```

In this case this build runs as expected, the images are properly created, even the container based on the image .../service-api:1.1.0 (the first image) runs just as planned. But when I try to run the container based on the image .../service-simulator:1.1.0 (the second image), I get the following error:

```
Setting Active Processor Count to 4
unable to determine class count
unable to walk /builds/<gitlab-project-path>/service-api
lstat /builds/<gitlab-project-path>/service-api: no such file or directory
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/memory-calculator': exit status 1
```

After running the container with '--entrypoint bash' in order to have a better look at the insides of the container, I can see that the path described in the error message `/builds/<gitlab-project-path>/service-api` doesn't exist. Instead, the existing path is the  `/builds/<gitlab-project-path>/service-simulator` which is the expected path since we have created an image for `service-simulator`.

The question is how and why does bellsoft-liberica layer sets the path inside memory-calculator and why does it happen after the first successful build? One hint I have is that it might have something to do with the image-layers created from the previous runs and that they wrong ones are somehow being used to create the later versions of the images. 

Thank you in advance!
