### DISCUSSION TITLE
SBOM for custom jlink JRE

### DISCUSSION THREAD

**Discussion by tortoiseparrot** [paketo-buildpacks/feedback#66] [Q&A]
Using Spring Boot and its Maven plugin to create an image with a custom JRE I'm a bit puzzled.

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <image>
            <env>
                <!-- https://github.com/paketo-buildpacks/amazon-corretto#configuration -->
                <BP_JVM_JLINK_ENABLED>true</BP_JVM_JLINK_ENABLED>
                <BP_JVM_JLINK_ARGS>--add-modules java.base,…,jdk.naming.dns --compress=2 --no-header-files --no-man-pages</BP_JVM_JLINK_ARGS>
            </env>
            <!-- use amazon-corretto instead of bellsoft-liberica, see https://github.com/spring-projects/spring-boot/issues/25561#issuecomment-795615788 -->
            <buildpacks>
                <buildpack>paketobuildpacks/amazon-corretto</buildpack>
                <buildpack>paketo-buildpacks/java</buildpack>
            </buildpacks>
        </image>
    </configuration>
</plugin>
```

From what I can tell so far this image is working as intended.
However I can't seem to find the JVM version in the SBOM and I believe that a Paketo buildback should have added it somewhere.

According to the build log:
```
Downloading from https://corretto.aws/downloads/resources/11.0.18.10.1/amazon-corretto-11.0.18.10.1-linux-x64.tar.gz
```

According to [paketo-buildpacks/amazon-corretto/buildpack.toml](https://github.com/paketo-buildpacks/amazon-corretto/blob/main/buildpack.toml):
```toml

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.18:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:11.0.18:*:*:*:*:*:*:*"]
    purl = "pkg:generic/amazon/corretto-jdk@11.0.18"
    sha256 = "40baac37cb9a3953bba01c07f34782bf4d80a7529009641278e42ca674ff9ee8"
    uri = "https://corretto.aws/downloads/resources/11.0.18.10.1/amazon-corretto-11.0.18.10.1-linux-x64.tar.gz"
    version = "11.0.18"
 ```
 
 I've downloaded the SBOM files using the `pack` CLI as per https://paketo.io/docs/howto/sbom/#access-syft-cyclonedx-and-spdx-sboms
 
 Now I would have expected to find the precise JVM version (11.0.18.10.1 / 11.0.18.10 / 11.0.18) somewhere.
 However the closest matches are `layers/sbom/launch/paketo-buildpacks_executable-jar/sbom.syft.json`:
 ```
"Java-Version": "11.0.13",
"Created-By": "11.0.11 (AdoptOpenJDK)",
"Build-Jdk": "11.0.2",
 ```
 
 I'm still reading up on SBOMs in general and the different formats, but none of those versions seem to be my buildpack runtime JRE version?
 Am I looking in the wrong places, is my specific use-case with custom jlink JRE unsupported for SBOM generation and if so - why?
